on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 10
          - 12
          - 14
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Run tests
        run: |
          npm install --also=dev
          npm test

  check-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run eslint
        run: |
          npm install --also=dev
          npm run lint

  publish:
    runs-on: ubuntu-latest
    needs:
      - run-tests
      - check-linting
    steps:
      - uses: actions/checkout@v2
      - name: Run semantic-release with commit linting
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install --also=dev
          semantic-release